### ISSUE TITLE
Uninstall missing argument

### ISSUE THREAD

**Issue by k4nfr3** [Yaxser/Backstab#2]
Hi, i know it's nearly cosmetic but
![image](https://user-images.githubusercontent.com/45294916/122225908-c554bf00-ceb5-11eb-83f7-349faac2fdd1.png)

Cheers

**Comment by Yaxser** [comment]
I'll fix this if I get more time later, thanks for reporting!

Note to self: this is happening now because I assume that the user will want to do something to a PID. However, maybe while testing and development users want to load\unload the driver.
