### ISSUE TITLE
I don't know why, but it didn't work

### ISSUE THREAD

**Issue by TidDl3R** [Yaxser/Backstab#5]
I tried to kill the process through PID, but it didn't work.
<img width="467" alt="25c500da931cc47c16056549a" src="https://user-images.githubusercontent.com/32321964/122520615-68d4d980-d046-11eb-9478-8409bdc29cbc.png">

Test on Windows 10 with administrator privilege.

**Comment by xuxuedong** [comment]
i tried to kill the two anti-virus process through PID, it both didn't work

![image](https://user-images.githubusercontent.com/9376976/122638801-cf322880-d128-11eb-86ce-299945905c2b.png)
test on windows 2012 r2 with administrator privilege

![image](https://user-images.githubusercontent.com/9376976/122638766-9c883000-d128-11eb-9e2d-234ac89c5de9.png)
test on windows 2008 r2 with administrator privilege

**Comment by Yaxser** [comment]
Hello to the both of you and thank you for reporting

@TidDl3R this is interesting, I noticed a bug in error reporting and after the fix we'll be able to have a better understanding of what is causing this? Are you building from source? I'll make a commit soon to fix the bug later this week and then we can continue investigating it.

@xuxuedong you are using the wrong argument prefix. Use` -f ` and `-p` instead of `/f` and `/p`

**Comment by xuxuedong** [comment]
@Yaxser what i use is -f and -p ):
![a](https://user-images.githubusercontent.com/9376976/122640031-baa55e80-d12f-11eb-8bc2-39470b31b27d.png)
![b](https://user-images.githubusercontent.com/9376976/122640035-c09b3f80-d12f-11eb-8205-9d4f76dba9eb.png)

**Comment by TidDl3R** [comment]
> Hello to the both of you and thank you for reporting
> 
> @TidDl3R this is interesting, I noticed a bug in error reporting and after the fix we'll be able to have a better understanding of what is causing this? Are you building from source? I'll make a commit soon to fix the bug later this week and then we can continue investigating it.
> 
> @xuxuedong you are using the wrong argument prefix. Use`-f` and `-p` instead of `/f` and `/p`

I used the version you pre-released, maybe it has some bugs that haven't been fixed?

**Comment by wgetnz** [comment]
> > 两位您好，感谢您的报告
> > @TidDl3R这很有趣，我注意到错误报告中有一个错误，修复后我们将能够更好地了解导致此问题的原因？你是从源代码构建的吗？我将在本周晚些时候提交修复该错误的提交，然后我们可以继续调查它。
> > @xuxuedong您使用了错误的参数前缀。使用`-f`and`-p`代替`/f`and`/p`
> 
> 我用的是你预发布的版本，可能有一些bug没有修复？

360会拦截未签名应用加载驱动，你尝试将应用进行数字签名后，在尝试杀死进程就可以了

**Comment by Yaxser** [comment]
@TidDl3R yes the release version isn't updated with the latest commit.

Someone made some nice changes and I want to accept his PR, make a few more changes, and then update the release version.

Can you maybe build from source? If yes then I can push a quick commit that will give more descriptive errors. Otherwise I'll update the release somewhere next week and let you know here 👍🏽

**Comment by Yaxser** [comment]
> > > 两位您好，感谢您的报告
> > > @TidDl3R这很有趣，我注意到错误报告中有一个错误，修复后我们将能够更好地了解导致此问题的原因？你是从源代码构建的吗？我将在本周晚些时候提交修复该错误的提交，然后我们可以继续调查它。
> > > @xuxuedong您使用了错误的参数前缀。使用`-f`and`-p`代替`/f`and`/p`
> > 
> > 
> > 我用的是你预发布的版本，可能有一些bug没有修复？
> 
> 360会拦截未签名应用加载驱动，你尝试将应用进行数字签名后，在尝试杀死进程就可以了

What is 360? Is it the endpoint protection software?

**Comment by wgetnz** [comment]
> > > > 您好，感谢您的报告
> > > > @TidDl3R这很成功，我注意到错误吗报告了一个错误，修复后我们将能够更好地了解导致此问题的原因？你是从源代码构建的？将在本周晚些时候提交修复该错误的提交，然后我们可以继续调查它。
> > > > @xuxuedong您使用了错误的参数前缀，使用`-f`和`-p`代替`/f`和`/p`
> > > 
> > > 
> > > 我用的是你预发布的版本，可能有一些bug没有修复？
> > 
> > 
> > 360会拦截未签名应用加载驱动，你尝试将应用数字签名后，在实验中进行过程就可以了
> 
> 什么是360？它是端点保护软件吗？

yes

**Comment by Yaxser** [comment]
@TidDl3R bug fixes are now published and released, you can download the release version and try it out
I'm curious about the outcome, please keep me posted!

**Comment by yaoh3i** [comment]
> @TidDl3R bug fixes are now published and released, you can download the release version and try it out
> I'm curious about the outcome, please keep me posted!

It works! Excellent tool. By the way, when I tried to kill some anti-virus software, there was a deadlock. These anti-virus software runs with system privileges and backstab runs with administrator privileges. Is that a problem? Or is backstab only for EDR?

**Comment by wgetnz** [comment]
> > @TidDl3R错误修复现已发布并发布，您可以下载发布版本并尝试一下
> > 我对结果很好奇，请随时关注我！
> 
> 有用！优秀的工具。顺便说一句，当我试图杀死一些杀毒软件时，出现了僵局。这些防病毒软件以系统权限运行，而 backstab 以管理员权限运行。那是问题吗？还是背刺仅适用于 EDR？

I have also encountered it, the process cannot be killed, it will get stuck，Sample installation address package: https://dl.360safe.com/setup.exe

Try to kill 360tray.exe after installation and running, it will get stuck


https://dl.360safe.com/360sd/360sd_x64_std_5.0.0.8183B.exe

360sd.exe  also

**Comment by yaoh3i** [comment]
> > > @TidDl3R错误修复现已发布并发布，您可以下载发布版本并尝试一下
> > > 我对结果很好奇，请随时关注我！
> > 
> > 
> > 有用！优秀的工具。顺便说一句，当我试图杀死一些杀毒软件时，出现了僵局。这些防病毒软件以系统权限运行，而 backstab 以管理员权限运行。那是问题吗？还是背刺仅适用于 EDR？
> 
> I have also encountered it, the process cannot be killed, it will get stuck，Sample installation address package: https://dl.360safe.com/setup.exe
> 
> Try to kill 360tray.exe after installation and running, it will get stuck
> 
> https://dl.360safe.com/360sd/360sd_x64_std_5.0.0.8183B.exe
> 
> 360sd.exe also

I tested 360 and other anti-virus software. Interestingly, after using backstab, the CPU utilization rate of 360 is as high as 98%, and it has lost the function of antivirus.

**Comment by wgetnz** [comment]
> > > > @TidDl3R错误修复现已发布并发布，您可以下载发布版本并尝试一下
> > > > 我对结果很好奇，请随时关注我！
> > > 
> > > 
> > > 有用！优秀的工具。顺便说一句，当我试图杀死一些杀毒软件时，出现了僵局。这些防病毒软件以系统权限运行，而 backstab 以管理员权限运行。那是问题吗？还是背刺仅适用于 EDR？
> > 
> > 
> > I have also encountered it, the process cannot be killed, it will get stuck，Sample installation address package: https://dl.360safe.com/setup.exe
> > Try to kill 360tray.exe after installation and running, it will get stuck
> > https://dl.360safe.com/360sd/360sd_x64_std_5.0.0.8183B.exe
> > 360sd.exe also
> 
> I tested 360 and other anti-virus software. Interestingly, after using backstab, the CPU utilization rate of 360 is as high as 98%, and it has lost the function of antivirus.

emmm...At the same time the system is also stuck

**Comment by Yaxser** [comment]
Hello everyone,

Since the original issue is resolved I'm going to close this issue, can you please create separate issues for any other observations and we can take a look at them there?

Cheers,
Yasser
