### ISSUE TITLE
Could not connect to ProcExp device: 5

### ISSUE THREAD

**Issue by wgetnz** [Yaxser/Backstab#6]
D:\Users\max\Desktop\git\Backstab-master\x64\Release>backstab.exe -n avpui.exe -k
no special driver dir specified, extracting to current dir
WriteResourceToDisk.CreateFile: 32
ConnectToProcExpDevice: 5
Could not connect to ProcExp device: 5

windows 10 1909 x64

**Comment by Yaxser** [comment]
You need to run it as an administrator
