### ISSUE TITLE
Could not connect to ProcExp device: 5

### ISSUE THREAD

**Issue by wgetnz** [Yaxser/Backstab#7]
not use administrator in cmd
C:\Users\mtest\Desktop>Backstab.exe -n OneDrive.exe -k -d c:\\driver2.sys
extracting the drive to c:\\driver2.sys
WriteResourceToDisk.CreateFile: 5
SetRegistryValues.RegCreateKeyExA: 1300
NtUnloadDriver.SetRegistryKeyValues: 1300
Could not load driver: 1300

C:\Users\mtest\Desktop>

---------------------------------------------------------------------
ues administrator in cmd 

C:\Users\mtest\Desktop>Backstab.exe -n OneDrive.exe -k -d c:\\driver2.sys
extracting the drive to c:\\driver2.sys
ConnectToProcExpDevice: 5
Could not connect to ProcExp device: 5

C:\Users\mtest\Desktop>

---------------------------------------------------------------------
ues administrator in posershell 

C:\Users\mtest\Desktop>Backstab.exe -n OneDrive.exe -k -d c:\\driver2.sys

extracting the drive to c:\\driver2.sys
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6
ProcExpKillHandle.DeviceIoControl: 6

------------------------------------------------------------------------------------
ues administrator in cmd 
C:\Users\mtest\Desktop>whoami /priv

特权信息
----------------------

特权名                                    描述                               状态
========================================= ================================== ======
SeIncreaseQuotaPrivilege                  为进程调整内存配额                 已禁用
SeSecurityPrivilege                       管理审核和安全日志                 已禁用
SeTakeOwnershipPrivilege                  取得文件或其他对象的所有权         已禁用
SeLoadDriverPrivilege                     加载和卸载设备驱动程序             已禁用
SeSystemProfilePrivilege                  配置文件系统性能                   已禁用
SeSystemtimePrivilege                     更改系统时间                       已禁用
SeProfileSingleProcessPrivilege           配置文件单一进程                   已禁用
SeIncreaseBasePriorityPrivilege           提高计划优先级                     已禁用
SeCreatePagefilePrivilege                 创建一个页面文件                   已禁用
SeBackupPrivilege                         备份文件和目录                     已禁用
SeRestorePrivilege                        还原文件和目录                     已禁用
SeShutdownPrivilege                       关闭系统                           已禁用
SeDebugPrivilege                          调试程序                           已禁用
SeSystemEnvironmentPrivilege              修改固件环境值                     已禁用
SeChangeNotifyPrivilege                   绕过遍历检查                       已启用
SeRemoteShutdownPrivilege                 从远程系统强制关机                 已禁用
SeUndockPrivilege                         从扩展坞上取下计算机               已禁用
SeManageVolumePrivilege                   执行卷维护任务                     已禁用
SeImpersonatePrivilege                    身份验证后模拟客户端               已启用
SeCreateGlobalPrivilege                   创建全局对象                       已启用
SeIncreaseWorkingSetPrivilege             增加进程工作集                     已禁用
SeTimeZonePrivilege                       更改时区                           已禁用
SeCreateSymbolicLinkPrivilege             创建符号链接                       已禁用
SeDelegateSessionUserImpersonatePrivilege 获取同一会话中另一个用户的模拟令牌 已禁用

C:\Users\mtest\Desktop>

我认为是cmd管理员权限中的SeDebugPrivilege 被禁用导致的问题，能否在程序中启用SeDebugPrivilege 检查? 或者在程序中启动SeDebugPrivilege 权限

**Comment by Yaxser** [comment]
Hello @wgetnz,

You are right, @k4nfr3 worked on a solution already and I merged his pull request so it should be fine now. Can you please test and confirm?

**Comment by wgetnz** [comment]
> 你好@wgetnz，
> 
> 你是对的，@k4nfr3已经在研究一个解决方案，我合并了他的拉取请求，所以现在应该没问题了。你能测试并确认吗？

It works fine

**Comment by Yaxser** [comment]
Credits go to @k4nfr3!
@wgetnz , thanks for your feed back, I'm gonna close this issue now.
